[general]
BROWSER = "chrome"
ELEMENT_OUTPUT_LOG = "user_friendly"
DO_NOT_RESTART = true
SOFT_RESTART = false

[custom]
SITE = 'https://fix-online.sbis.ru/page/dialogs'
LOGIN = "sync_test_auto_1"
PASSWORD = "Авто123"
